characters:
  first: 0x803d64
  last_playable: 0x804620
  last: 0x8070fc

  # Total bytes of memory a character takes up
  total_bytes: 0x34

  # Num bytes from start of character to class byte
  class_offset: 0x5

  # Num bytes from start of character to first base stat
  base_offset: 0xb
  num_bases: 9

  # Num bytes from start of character to first growth rate
  growth_offset: 0x1c
  num_growths: 7

  # Avoid byte positions of non-boss enemy characters
  others: [0x1b, 0x2d, 0x2e, 0x2f, 0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x41, 0x49, 0x50, 0x55, 0x56, 0x58, 0x59, 0x5c, 0x5d, 0x5e, 0x5f, 0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a, 0x7b, 0x7c, 0x7d, 0x7e, 0x7f, 0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8a, 0x8b, 0x8c, 0x8d, 0x8e, 0x8f, 0x90, 0x91, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9a, 0x9b, 0x9c, 0x9d, 0x9e, 0x9f, 0xa0, 0xa1, 0xa2, 0xa3, 0xa4, 0xa5, 0xa6, 0xa7, 0xa8, 0xa9, 0xaa, 0xab, 0xac, 0xad, 0xae, 0xaf, 0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe, 0xbf, 0xc0, 0xc1, 0xc2, 0xc3, 0xc4, 0xc6, 0xcd, 0xce, 0xcf, 0xd0, 0xd1, 0xd2, 0xd3, 0xd4, 0xd5, 0xd6, 0xd7, 0xd8, 0xd9, 0xda, 0xdb, 0xdc, 0xdd, 0xde, 0xdf, 0xe0, 0xe1, 0xe2, 0xe3, 0xe4, 0xe5, 0xe6, 0xe7, 0xe8, 0xe9, 0xea, 0xeb, 0xec, 0xed, 0xee, 0xef, 0xf0, 0xf1, 0xf2, 0xf3, 0xf4, 0xf5, 0xf6, 0xf7, 0xf8, 0xf9, 0xfa, 0xfb, 0xfc, 0xfd, 0xfe, 0xff]

  # Item byte positions for all named characters
  characters:
    # Name
      # Character Identifier
      # Is character NPC
      # List of character starting locations
        # Location of Item: Item ID
    O'Neill:
      id: 0x68
      npc: true
      starting_locations:
        - 0x8b3c5c: 0x1f
    Seth:
      id: 0x02
      item_pos:
        - 0x8b3c20: 0x3
        - 0x8b3c21: 0x17
    Eirika:
      id: 0x01
      item_pos:
        - 0x8c72d0: 0x9
        - 0x8c72d1: 0x2
    Franz:
      id: 0x04
      item_pos:
        - 0x8b4188: 0x1
        - 0x8b4189: 0x14
    Gilliam:
      id: 0x03
      item_pos:
        - 0x8b419c: 0x14
    Breguet:
      id: 0x46
      npc: true
      item_pos:
        - 0x8b40e8: 0x14
    Moulder:
      id: 0x05
      item_pos:
        - 0x8b4328: 0x4b
    Bone:
      id: 0x47
      npc: true
      item_pos:
        - 0x8b4378: 0x1f
    Vanessa:
      id: 0x06
      item_pos:
        - 0x8b4418: 0x15
        - 0x8b4419: 0x1c
    Ross:
      id: 0x07
      item_pos:
        - 0x8b4449: 0x2c
    Garcia:
      id: 0x0a
      item_pos:
        - 0x8b4454: 0x1f
        - 0x8b4455: 0x28
    Neimi:
      id: 0x08
      item_pos:
        - 0x8b45f8: 0x2d
    Colm:
      id: 0x09
      item_pos:
        - 0x8b4724: 0x1
    Bazba:
      id: 0x48
      npc: true
      item_pos:
        - 0x8b4648: 0x20
        - 0x8b4649: 0x28
    Lute:
      id: 0x0c
      item_pos:
        - 0x8b4c08: 0x38
    Artur:
      id: 0x13
      item_pos:
        - 0x8b4924: 0x3f
    Ephraim:
      id: 0x0f
      item_pos:
        - 0x8b5a70: 0x78
        - 0x8b5a71: 0x16
        - 0x8bcaf4: 0x78
        - 0x8bcaf5: 0x16
    Forde:
      id: 0x10
      item_pos:
        - 0x8b5a84: 0x3
        - 0x8b5a85: 0x1c
    Kyle:
      id: 0x11
      item_pos:
        - 0x8b5a98: 0x1
        - 0x8b5a99: 0x16
    Orson:
      id: 0x42
      item_pos:
        - 0x8b5aac: 0x4
        - 0x8b5aad: 0x16
        - 0x8bcf68: 0x1d
        - 0x8bcf69: 0x4
        - 0x8c7758: 0x11
        - 0x8c7759: 0x17
    Zonta:
      id: 0x6a
      npc: true
      item_pos:
        - 0x8b5b10: 0x6
    Natasha:
      id: 0x0d
      item_pos:
        - 0x8b59d4: 0x4c
    Saar:
      id: 0x4a
      npc: true
      item_pos:
        - 0x8b5704: 0x1c
    Joshua:
      id: 0x20
      item_pos:
        - 0x8b5920: 0xd
    Novala:
      id: 0x4b
      npc: true
      item_pos:
        - 0x8b6308: 0x45
    Murray:
      id: 0x4c
      npc: true
      item_pos:
        - 0x8b70a0: 0x3
        - 0x8b70a1: 0x1c
    Tirado:
      id: 0x4d
      npc: true
      item_pos:
        - 0x8b73d4: 0x17
        - 0x8b73d5: 0x1c
    Tana:
      id: 0x22
      item_pos:
        - 0x8b7c2c: 0x95
        - 0x8b7c2d: 0x1c
    Binks:
      id: 0x43
      npc: true
      item_pos:
        - 0x8b7d08: 0x20
        - 0x8b7d09: 0x2e
    Amelia:
      id: 0x12
      item_pos:
        - 0x8b8104: 0x15
        - 0x8c26bc: 0x15
        - 0x8c289c: 0x15
    Innes:
      id: 0x0b
      item_pos:
        - 0x8b8998: 0x2f
        - 0x8c72e4: 0x2f
    Gerik:
      id: 0x0f
      item_pos:
        - 0x8b89ac: 0x6
        - 0x8c52a8: 0x6
    Tethys:
      id: 0x15
      item_pos:
        - 0x8b89c3: 0x1 # Assume iron weapon
        - 0x8c5296: 0x1
    Pablo:
      id: 0x4f
      npc: true
      item_pos:
        - 0x8b8650: 0x41
    Marisa:
      id: 0x16
      item_pos:
        - 0x8b8830: 0xc
        - 0x8c48b8: 0xc
    Ewan:
      id: 0x18
      item_pos:
        - 0x8ba5dc: 0x38
        - 0x8c4ac0: 0x38
    Saleh:
      id: 0x17
      item_pos:
        - 0x8ba190: 0x3a
        - 0x8ba191: 0x39
        - 0x8c72f8: 0x3a
        - 0x8c72f9: 0x39
    Cormag:
      id: 0x0e
      item_pos:
        - 0x8baee0: 0x1a
        - 0x8baee1: 0x16
        - 0x8c305c: 0x14
        - 0x8c305c: 0x1a
    Aias:
      id: 0x51
      npc: true
      item_pos:
        - 0x8baa58: 0x96
        - 0x8baa59: 0x7
        - 0x8baa5a: 0x2b
    Carlyle:
      id: 0x52
      npc: true
      item_pos:
        - 0x8bbfd8: 0xa1
    Rennac:
      id: 0x1d
      item_pos:
        - 0x8bbf9c: 0x3
        - 0x8c6478: 0x3
    Knoll:
      id: 0x1f
      item_pos:
        - 0x8bcae0: 0x45
        - 0x8bcae1: 0x47
        - 0x8c6450
    Duessel:
      id: 0x1d
      item_pos:
        - 0x8bcb08: 0x21
        - 0x8bcb09: 0x16
        - 0x8c2fbc: 0x21
        - 0x8c2fbd: 0x16
    Valter:
      id: 0x43
      npc: true
      item_pos:
        - 0x8bc720: 0x1d
        - 0x8bc721: 0x1a
        - 0x8c6f24: 0x1d
        - 0x8c6f25: 0x1a
    Caellach:
      id: 0x53
      npc: true
      item_pos:
        - 0x8bc8ec: 0x29
        - 0x8bc8ed: 0x21
        - 0x8c47c8: 0x29
        - 0x8c47c9: 0x21
        - 0x8c721c: 0x29
        - 0x8c721d: 0x21
    Myrrh:
      id: 0x1e
      item_pos:
        - 0x8bcea0: 0xaa
        - 0x8c771c: 0xaa
    Lyon:
      id: 0x40
      npc: true
      item_pos:
        - 0x8b3120: 0x49
        - 0x8b3121: 0x47
        - 0x8c192c: 0x8f
        - 0x8c7f64: 0x49
        - 0x8c7f65: 0x47
        - 0x8cb170: 0x8f
    Syrene:
      id: 0x21
      item_pos:
        - 0x8be170: 0x17
        - 0x8be171: 0x1c
    Riev:
      id: 0x57
      npc: true
      item_pos:
        - 0x8c0404: 0x43
        - 0x8c0efc: 0x43
        - 0x8c9e24: 0x43
        - 0x8ca7c4: 0x43
    Morva:
      id: 0x41
      npc: true
      item_pos:
        - 0x8c12a8: 0x90
        - 0x8cab70: 0x90
    Demon King:
      id: 0xbe
      npc: true
      item_pos:
        - 0x8c20a4: 0xa8
        - 0x8c20a5: 0xa9
        - 0x8c20a6: 0xa6
    Gheb:
      id: 0x5a
      npc: true
      item_pos:
        - 0x8c23c4: 0x1f
        - 0x8c23c5: 0x24
    Beran:
      id: 0x5b
      npc: true
      item_pos:
        - 0x8c2e04
    Selena:
      id: 0x44
      item_pos:
        - 0x8c2d50: 0x3b
        - 0x8c2d51: 0x3a
        - 0x8c4fb0: 0x3b
        - 0x8c4fb1: 0x3a
    Vigarde:
      id: 0x6b
      item_pos:
        - 0x8c60cc: 0x1d
    L'Arachel:
      id: 0x19
      item_pos:
        - 0x8b9cd8
        - 0x8c403c
    Dozla:
      id: 0x1a
      item_pos:
        - 0x8b9cec
        - 0x8c4028
classes:
  total: 0x7F
  staff only: [0x45, 0x4a, 0x4b]
  other: [0x00, 0x34, 0x50, 0x62, 0x67, 0x68, 0x69, 0x6a, 0x6b, 0x6c, 0x6d, 0x6e, 0x6f, 0x70, 0x71, 0x72, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7a 0x7b]

items:
  prf:
    - 0x6 # Rapier
    - 0x78 # Reginleif
    - 0x8f # Naglfar
  e:
    0x0: # sword
      - 0x1
      - 0x2
      - 0xe
      - 0x81
    0x1: # lance
      - 0x14
      - 0x15
      - 0x18
      - 0x1c
      - 0x82
    0x2: # axe
      - 0x1f
      - 0x20
      - 0x27
      - 0x28
      - 0x2c
      - 0x83
    0x3: # bow
      - 0x2d
      - 0x84
    0x4: # staff
      - 0x4b
    0x5: # anima
      - 0x38
    0x6: # light
      - 0x3f
    0xb: # dragonstone/monster
      - 0x8b
  d:
    0x0: # sword
      - 0x3
      - 0x5
      - 0x8
      - 0x9
      - 0xc
      - 0xd
      - 0x13
    0x1: # lance
      - 0x16
      - 0x1b
      - 0x95
    0x2: # axe
      - 0x22
      - 0x25
      - 0x26
    0x3: # bow
      - 0x2e
      - 0x30
      - 0x33
      - 0x34
    0x4: # staff
      - 0x4c
      - 0x56
      - 0x58
    0x5: # anima
      - 0x39
    0x6: # light
      - 0x40
    0x7: # dark
      - 0x45
  c:
    0x0: # sword
      - 0x6
      - 0xf
      - 0x10
      - 0x12
      - 0x1e
    0x1: # lance
      - 0x1a
      - 0x8d
      - 0x96
    0x2: # axe
      - 0x24
      - 0x2a
      - 0x2b
      - 0x5a
    0x3: # bow
      - 0x31
    0x4: # staff
      - 0x4d
      - 0x50
      - 0x57
      - 0x59
    0x5: # anima
      - 0x3a
    0x6: # light
      - 0x41
    0x7: # dark
      - 0x46
      - 0x47
  b:
    0x0: # sword
      - 0xb
      - 0xa1
    0x1: # lance
      - 0x19
      - 0x1d
    0x2: # axe
      - 0x23
      - 0x86
    0x3: # bow
      - 0x32
    0x4: # staff
      - 0x4e
      - 0x51
      - 0x52
      - 0x53
      - 0x55
      - 0xa1 # Demon King Nightmare
    0x5: # anima
      - 0x3b
    0x6: # light
      - 0x42
    0x7: # dark
      - 0x48
      - 0xab
      - 0xac
      - 0xb3
      - 0xb4
      - 0xb5
    0xb: # Dragonstone/Monster
      - 0xa8
      - 0xa9
      - 0xaa
      - 0xad
      - 0xae
      - 0xaf
      - 0xb0
      - 0xb1
      - 0xb2
  a:
    0x0: # sword
      - 0x4
      - 0x7
      - 0x11
    0x1: # lance
      - 0x17
    0x2: # axe
      - 0x21
      - 0x29
    0x3: # bow
      - 0x2f
    0x4: # staff
      - 0x4f
      - 0x54
    0x5: # anima
      - 0x3c
    0x6: # light
      - 0x43
    0x7: # dark
      - 0x49
    0xb: # Dragonstone/Monster
      - 0x90
  promotion:
    master_seal: 0x80ae30
    icon_offset: 0x1d
    usage_offset: 0x1e
    others:
      - 0x80a920 # Hero Crest
      - 0x80a944 # Knight Crest
      - 0x80a968 # Orion's Bolt
      - 0x80a98c # Elysian Whip
      - 0x80a9b0 # Guiding Ring
      - 0x80b04c # Ocean Seal
