randomize:
  mix_promotes:
      enabled: false
  stats:
    bases:
      playable:
        enabled: false
        minimum: 0
        maximum: 30
      boss:
        enabled: false
        minimum: 0
        maximum: 30
      other:
        enabled: false
        minimum: 0
        maximum: 30
      class:
        enabled: false
        minimum: 0
        maximum: 30
    growths:
      playable:
        enabled: false
        minimum: 0
        maximum: 255
      boss:
        enabled: false
        minimum: 0
        maximum: 255
      other:
        enabled: false
        minimum: 0
        maximum: 255

  classes:
    mode: Combat
    all_master_seals:
      enabled: true
    playable:
      enabled: true
    boss:
      enabled: true
    other:
      enabled: true

modify:
  stats:
    bases:
      playable:
        enabled: false
        modifier: -5
      boss:
        enabled: false
        modifier: +5
      other:
        enabled: false
        modifier: +5
    growths:
      playable:
        enabled: false
        modifier: -10
      boss:
        enabled: false
        modifier: +5
      other:
        enabled: false
        modifier: +5

rom_path: null
