"""
DO NOT EDIT THIS FILE!!!!

This is an auto-generated file for bundling Fire Emblem 7
save data into memory instead of on disk.

Instead, please run "./tools/generate.py"
to create a configuration file
"""

# pylint: disable=too-many-lines,too-few-public-methods,line-too-long

class FE7SaveData:
    """Class for holding FE7 save data"""

    def __init__(self):
        self.__data = FE7DATAPLACEHOLDER

    def get_data(self):
        """Retrieve the save data"""
        return self.__data
