"""
DO NOT EDIT THIS FILE!!!!

This is an auto-generated file for bundling the Fire
Emblem configs into memory instead of on disk.

Instead, please run "./tools/generate_specs.py"
to create a configuration file
"""

# pylint: disable=too-many-lines
from enum import Enum

class Spec(dict, Enum):
    """ Spec enumeration """

    FE6 = FE6PLACEHOLDER
    FE7 = FE7PLACEHOLDER
    FE8 = FE8PLACEHOLDER
